################################################################
# Create dynamic reports using Radiant and the shinyAce editor
################################################################
rmd_switch <- c(
  "Switch tab" = "switch", 
  "Don't switch tab" = "no_switch"
)
rmd_generate <- c(
  "Auto paste" = "auto",
  "Manual paste" = "manual"
)
rmd_save_type <- c("Notebook", "HTML", "PDF", "Word", "Rmd")
rmd_set <- c("To Rmd", "auto", "manual")
rmd_set_rstudio <- c("To Rmd", "To R")

if (rstudioapi::isAvailable()) {
  rmd_generate <- c(
    "Auto paste" = "auto",
    "Manual paste" = "manual",
    "To Rstudio (Rmd)" = "To Rmd",
    "Use Report > R" = "Use R"
  )
} else if (!isTRUE(rmarkdown::pandoc_available())) {
  rmd_save_type <- c("HTML", "Rmd")
}

## can still save report, code, and data without permission to run code
if (!getOption("radiant.report")) {
  rmd_save_type <- "Rmd"
}

if (Sys.getenv("R_ZIPCMD") != "") {
  rmd_save_type <- c(rmd_save_type, "Rmd + Data (zip)")
}

rmd_view_options <- c(
  "Dual view" = "dual",
  "Preview only" = "pr_only",
  "Editor only" = "ed_only"
)

rmd_example <- "## Sample report

This is an example of the type of report you can write in Radiant.

* You can create
* bullet lists

1. And numbered
2. lists

Note: Markdown is used to format the report. Go to [commonmark.org](http://commonmark.org/help/) for an interactive tutorial.

### Math

You can even include math if you want:

$$y_t = \\alpha + \\beta x_t + \\epsilon_t.$$

To show the output press the `Knit report (Rmd)` button.

### Tables

To generate a table that will display properly in both PDF and HTML you can use a layout similar to the example below:

Year  |  Outcome  |  Prior probability
:---- | --------: | :----------------------:
2013  | Win       |  0.30
2014  | Loss      |  0.25
2015  | Win       |  0.20

Note that the columns are left-aligned, right-aligned, and centered using a `:`. Alternatively you can create a `tibble` with the information to be put in the table and use `knitr`'s `kable` function to generate the desired output. See example below:

```{r}
tbl <- tibble::tibble(
  Year = c(2013, 2014, 2015),
  Outcome = c(\"Win\", \"Loss\", \"Win\"),
  `Prior probability` = c(0.30, 0.25, 0.20)
)

knitr::kable(tbl, align = \"ccc\")
```

To align the columns use `l` for left, `r` for right, and `c` for center. In the example above each column is centered. For additional information about formatting tables see
https://www.rforge.net/doc/packages/knitr/kable.html

It is also possible to generate interactive tables using the DT package. In Radiant you can use the `dtab` function to display a data.frame as a nicely formatted table:

```{r}
dtab(tbl) %>% render()
```

The DT package has various [formatting options](http://rstudio.github.io/DT/functions.html). For example, to remove the filter boxes and display the `Prior probability` column as a percentage we could use the command below:

```{r}
dtab(tbl, filter = \"none\") %>%
  DT::formatPercentage(\"Prior probability\", 1) %>%
  render()
```

### Documenting analysis results in Radiant

The report feature in Radiant should be used in conjunction with the <i title='Report results' class='fa fa-edit'></i> icons shown at the bottom of the side bar on (almost) all pages. When that icon is clicked the command used to create the ouput is copied into the editor in the _Report > Rmd_ tab. By default Radiant will paste the code generated for the analysis you just completed at the bottom of the report (i.e., `Auto paste`). However, you can turn off that feature by selecting `Manual paste` from the dropown. With manual paste on, the code is put in the clipboard when you click a report icon and you can paste it where you want in the _Report > Rmd_ editor window.

By clicking the `Knit report (Rmd)` button or pressing CTRL-enter (CMD-enter on Mac), the output from the analysis will be recreated. You can add text, bullets, headers, etc. around the code blocks to describe and explain the results using <a href='http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html' target='_blank'>markdown</a>. You can also select part of the report you want to render.

Below is some code generated by Radiant to produce a scatterplot / heatmap of the price of diamonds versus carats. The colors in the plot reflect the clarity of the diamond.

```{r fig.width = 7, fig.height = 5, dpi = 96}
visualize(
  dataset = \"diamonds\", 
  xvar = \"carat\", 
  yvar = \"price\", 
  type = \"scatter\", 
  color = \"clarity\", 
  custom = TRUE
) +
labs(
  title = \"Diamond prices\", 
  x = \"Carats\", 
  y = \"Price ($)\"
)
```

> **Put your own code here or delete this sample report and create your own**

"

## allow running code through button or keyboard shortcut
report_rmd <- reactiveValues(report = 0, knit_button = 0, clear = 0)

output$ui_rmd_generate <- renderUI({
  isolate({
    init <- ifelse (state_init("r_generate", "Use Rmd") != "Use Rmd", "Use R", "auto")
  })
  selectInput(
    inputId = "rmd_generate", 
    label = NULL,
    choices = rmd_generate,
    # selected = state_init("rmd_generate", "auto"),
    selected = state_init("rmd_generate", init),
    multiple = FALSE, 
    selectize = FALSE,
    width = "140px"
  )
})

output$ui_rmd_view <- renderUI({
  req(input$rmd_generate)
  selectInput(
    "rmd_view", label = NULL, choices = rmd_view_options,
    selected = state_init("rmd_view", "dual"),
    multiple = FALSE, selectize = FALSE, width = "120px"
  )
})

# observeEvent(input$rmd_generate, {
#   if (input$rmd_generate == "To Rmd") {
#     updateSelectInput(session, "rmd_switch", selected = "no_switch")
#     updateSelectInput(session, "rmd_view", selected = "pr_only")
#     # report_rmd$rmd <- 0

#   } else if (input$rmd_generate == "Use Report > R") {

#     if (isTRUE(input$r_generate == "Use Report > Rmd")) {
#       updateSelectInput(session, "r_generate", selected = "auto")
#     }
#     updateTabsetPanel(session, "nav_radiant", selected = "R")
#     # updateSelectInput(session, "rmd_generate", selected = "auto")
#   } else {
#     updateSelectInput(session, "rmd_switch", selected = "switch")
#     updateSelectInput(session, "rmd_view", selected = "dual")
#   }
# })

observeEvent(input$rmd_generate, {
  if (isTRUE(input$rmd_generate == "To Rmd")) {

    updateSelectInput(session, "rmd_switch", selected = "no_switch")
    updateSelectInput(session, "rmd_view", selected = "pr_only")
    report_rmd$clear <- 1

    ## get info from rstudio editor
    cnt <- rstudio_context(type = "rmd")
    if (is_empty(cnt$path) || cnt$ext != "rmd") {
      rmd <- r_state$radiant_rmd_name
      if (!is_empty(rmd)) {
        if (file.exists(rmd)) {
          ## useful if you are not using an Rstudio project
          rstudioapi::navigateToFile(rmd)
        } else {
          pdir <- getOption("radiant.project_dir", default = "") 
          path <- file.path(pdir, rmd) 
          if (file.exists(path)) {
            rstudioapi::navigateToFile(path)
          }
        }
      } else {

        ## popup to suggest user create an .Rmd file
        showModal(
          modalDialog(
            title = "Radiant to Rmd (Rstudio)",
            span(
              "Radiant is set to use an rmarkdown document in Rstudio 
              ('To Rstudio (Rmd)'). However, the active document in 
              Rstudio does not seem to be of type .Rmd. Please open an 
              existing .Rmd file or create a new one in Rstudio. The 
              file must be saved to disk before it can be accessed. If 
              you want to use the editor in Radiant instead, change 
              'To Rstudio (Rmd)' to 'Auto paste' or 'Manual paste'."
            ),
            footer = modalButton("OK"),
            size = "s",
            easyClose = TRUE
          )
        )
      }
    }
  # } else if (input$rmd_generate == "Use R") {
  } else if (state_init("rmd_generate", "auto") == "Use R") {
    # if (isTRUE(input$rmd_generate == "Use R")) {
    if (state_init("r_generate", "auto") == "Use Rmd") {
    # if (isTRUE(input$r_generate == "Use Rmd")) {
      updateSelectInput(session, "r_generate", selected = "auto")
    }
    # updateTabsetPanel(session, "nav_radiant", selected = "R")
  } else {
    updateSelectInput(session, "rmd_switch", selected = "switch")
    updateSelectInput(session, "rmd_view", selected = "dual")
  }
})

output$ui_rmd_switch <- renderUI({
  req(input$rmd_generate)
  selectInput(
    inputId = "rmd_switch", label = NULL,
    choices = rmd_switch,
    selected = state_init("rmd_switch", "switch"),
    multiple = FALSE, selectize = FALSE,
    width = "140px"
  )
})

## would like to put result straight to Rstudio if possible
# observeEvent(input$rmd_load, {
#   if (input$rmd_generate %in% rmd_set_rstudio) {
#     updateSelectInput(session, "rmd_generate", selected = "auto")
#   }
# })

output$ui_rmd_save_type <- renderUI({
  # req(input$rmd_generate)

  # if (input$rmd_generate %in% rmd_set) {
  #   rmd_save_type <- setdiff(rmd_save_type, c("R", "R + Data (zip)"))
  # } else {
  #   rmd_save_type <- setdiff(rmd_save_type, c("Rmd", "Rmd + Data (zip)"))
  # }

  selectInput(
    inputId = "rmd_save_type", label = NULL,
    choices = rmd_save_type,
    selected = state_init("rmd_save_type", rmd_save_type[1]),
    multiple = FALSE, selectize = FALSE,
    width = "140px"
  )
})

output$ui_rmd_save <- renderUI({
  if (isTRUE(getOption("radiant.report"))) {
    # if (exists(".rs.readUiPref") && .rs.readUiPref("shiny_viewer_type") == 2) {
    if (isTRUE(getOption("radiant.launch", "browser") == "browser")) {
      ## using a download handler
      downloadButton("rmd_save", "Save report", class = "btn-primary")
    } else {
      actionButton("rmd_save", "Save report", icon = icon("download"), class = "btn-primary")
    }
  } else {
    invisible()
  }
})

output$ui_rmd_load <- renderUI({
  if (isTRUE(getOption("radiant.launch", "browser") == "browser")) {
    # fileInput("rmd_load", "", multiple = FALSE, accept = c(".Rmd", ".rmd", ".md", ".html"))
    file_upload_button(
      "rmd_load", 
      accept = c(".Rmd", ".rmd", ".md", ".html"),
      buttonLabel = "Load report" 
      # class = "btn-primary"
    )
  } else {
    actionButton("rmd_load", "Load report", icon = icon("upload"))
  }
})

output$ui_rmd_read_files <- renderUI({
  if (isTRUE(getOption("radiant.launch", "browser") == "browser")) {
    invisible()
  } else {
    actionButton("rmd_read_files", "Read files", icon = icon("book"), class = "btn-primary")
  }
})

# observe({
#   ## see viz ui
#   input$rmd_edit
#   isolate({
#     print(attr(rmd_knitted, "observable")$.invalidated)
#   })

#   ## notify user when the report needs to be updated
#   ## based on https://stackoverflow.com/questions/45478521/listen-to-reactive-invalidation-in-shiny
#   if (report_rmd$report != 1) {
#     if (isTRUE(attr(rmd_knitted, "observable")$.invalidated)) {
#       updateActionButton(session, "rmd_knit", "Update report", icon = icon("refresh", class = "fa-spin"))
#     } else {
#       updateActionButton(session, "rmd_knit", "Knit report", icon = icon("play"))
#     }
#   }
# })

output$report_rmd <- renderUI({
  # init <- isolate({
  #   if (is_empty(input$rmd_edit)) {
  #     rmd_example 
  #   } else {
  #     esc_slash(input$rmd_edit)
  #   }
  # })
  tagList(
    with(
      tags,
      table(
        td(help_modal(
          "Report > Rmd", "rmd_help",
          inclMD(file.path(getOption("radiant.path.data"), "app/tools/help/report_rmd.md"))
        )),
        td(HTML("&nbsp;&nbsp;")),
        td(
          actionButton(
            "rmd_knit", " Knit report (Rmd)", icon = icon("play"), 
            class = "btn-success"
            # focus doesn't seem to work https://stackoverflow.com/questions/7050931/how-to-set-focus-on-the-ace-editor
            # class = "btn-success", onclick = "function() {$('#rmd_edit').focus();}"
            # class = "btn-success", onclick = "function() {$('editor__rmdedit').focus();}"
          ), style = "padding-top:5px;" 
        ),
        td(uiOutput("ui_rmd_generate")),
        td(uiOutput("ui_rmd_view")),
        td(uiOutput("ui_rmd_switch")),
        td(uiOutput("ui_rmd_save_type")),
        td(uiOutput("ui_rmd_save"), style = "padding-top:5px;"),
        td(uiOutput("ui_rmd_load"), style = "padding-top:5px;"),
        td(uiOutput("ui_rmd_read_files"), style = "padding-top:5px;"),
        td(actionButton("rmd_clear", "Clear output", icon = icon("trash"), class = "btn-danger"), style = "padding-top:5px;")
        # td(shinyFiles::shinyFilesButton("my_shiny_file", "Select data", "Select one or more datasets", TRUE), style = "padding-top:5px;")
      )
    ),
    shinyAce::aceEditor(
      "rmd_edit", 
      selectionId = "rmd_edit_selection",
      mode = "markdown",
      theme = getOption("radiant.ace_theme", default = "tomorrow"),
      wordWrap = TRUE, 
      height = "auto", 
      value = state_init("rmd_edit", rmd_example) %>% esc_slash(),
      vimKeyBinding = getOption("radiant.vim.keys", default = FALSE),
      hotkeys = list(rmd_hotkey = list(win = "CTRL-ENTER", mac = "CMD-ENTER")),
      autoComplete = "live"
    ),
    htmlOutput("rmd_knitted"),
    getdeps()
  )
})

rmd_edit_auto <- shinyAce::aceAutocomplete("rmd_edit")

## doesn't seem necessary
# observe({
#   rmd_edit_auto$resume()
# })

## see ?shinyAce::aceAutocomplete
# observe({
#   print(input$shinyAce_rmd_edit_hint)
# })

observeEvent(input$rmd_knit, {
  ## hack to allow processing current line
  report_rmd$knit_button <- 1
})

observeEvent(input$rmd_clear, {
  ## hack to allow clearing output
  ## see https://groups.google.com/d/msg/shiny-discuss/PiU6PzQ_iSc/NsJkSDDCmlwJ
  report_rmd$clear <- 1
})

observe({
  input$rmd_hotkey
  if (!is.null(input$rmd_knit)) {
    isolate({
      report_rmd$report <- report_rmd$report + 1
      report_rmd$clear <- 0
    })
  }
})

# observe({
  # print(input$rmd_generate)
  # print(input$rmd_view)
  # print("\n--- rmd knit ----")
  # print(input$rmd_knit)
  # print(input$rmd_hotkey)
  # print(toList(report_rmd))
  # print("----------------------")

  # print("\n--- rmd lines ----")
  # print(input$rmd_current_line)
  # print(input$rmd_current_line_content)
  # print(input$rmd_edit_selection)
  # print(input$rmd_hotkey)
  # print("----------------------")
# })

output$rmd_view <- renderUI({
  req(input$rmd_generate, input$rmd_view)
  if (input$rmd_view == "ed_only") {
    tags$head(tags$style(
      HTML("#rmd_edit {right: 0; left: 0;} #rmd_knitted {left: 200%; right: -100%;}")
    ))
  } else if (input$rmd_view == "pr_only") {
    tags$head(tags$style(
      HTML("#rmd_edit {right: 200%; left: -100%;} #rmd_knitted {left: 0; right: 0;}")
    ))
  } else {
    tags$head(tags$style(
      HTML("#rmd_edit {right: 50%; left: 0;} #rmd_knitted {left: 50%; right: 0;}")
    ))
  }
})

rmd_knitted <- eventReactive(report_rmd$report != 1, {
  if (!isTRUE(getOption("radiant.report"))) {
    HTML("<h2>Report was not evaluated. If you have sudo access to the server set options(radiant.report = TRUE) in .Rprofile for the shiny user </h2>")
  } else {
    withProgress(message = "Knitting report", value = 1, {
      if (isTRUE(input$rmd_generate == "To Rmd")) {

        cnt <- rstudio_context(type = "rmd")
        if (is_empty(cnt$path) || is_empty(cnt$ext, "r")) {

          ## popup to suggest user create an .Rmd file
          showModal(
            modalDialog(
              title = "Report Rstudio (Rmd)",
              span(
                "Report is set to use an rmarkdown document in Rstudio 
                ('To Rstudio (Rmd)'). Please check that you have an .Rmd file 
                open in Rstudio and that the file has been saved to disk.
                If you want to use the editor in Radiant instead, change 
                'To Rstudio (Rmd)' to 'Auto paste' or 'Manual paste'."
              ),
              footer = modalButton("OK"),
              size = "s",
              easyClose = TRUE
            )
          )
          report <- ""
        } else {
          if (cnt$path != cnt$rpath) {
            r_state$radiant_rmd_name <<- cnt$rpath
          } else {
            r_state$radiant_rmd_name <<- cnt$path
          }
          report <- cnt$content
        }
      } else if (!is_empty(input$rmd_edit)) {
        if (!is_empty(input$rmd_edit_selection, "")) {
          report <- input$rmd_edit_selection
        } else if (!is_empty(input$rmd_hotkey$line, "") && report_rmd$knit_button == 0) {
          report <- input$rmd_hotkey$line
        } else {
          report <- input$rmd_edit
          ## hack to allow processing current line
          report_rmd$knit_button <- 0
        }

      }
      knit_it(report, type = "rmd")
    })
  }
})

output$rmd_knitted <- renderUI({
  req(report_rmd$report != 1 && report_rmd$clear == 0)
  rmd_knitted()
})

## keep track of file and report names
# observe({
#   report_rmd
  
#   # report_rmd$rmd
#   # report_rmd$rcode
#   input$r_save
#   input$rmd_save
#   # input$rmd_save_dh
  # print("===================")
  # print(r_state$radiant_state_name)
  # print(r_state$radiant_rmd_name)
  # print(r_state$radiant_r_name)
  # print("===================")

#   # print(getOption("radiant.project_dir"))
#   # print(getOption("radiant.write_dir"))
#   # print(getOption("radiant.dropbox_dir"))
#   # print(getOption("radiant.gdrive_dir"))
#   # print("===================")
# })

if (isTRUE(getOption("radiant.launch", "browser") == "browser")) {
  ## based on http://shiny.rstudio.com/gallery/download-knitr-reports.html
  output$rmd_save <- downloadHandler(
    filename = function() {
      report_save_filename(type = "rmd", full.name = FALSE)
    },
    content = function(file) {
      report_save_content(file, type = "rmd") 
    }
  )
} else {
  observeEvent(input$rmd_save, {
    ## saving rmd report to disk
    path <- report_save_filename(type = "rmd", full.name = TRUE)
    path <- rstudioapi::selectFile(
      caption = "Report file name",
      path = path,
      filter = "Report file name (*)",
      existing = FALSE
    )
    if (!is(path, "try-error") && !is_empty(path)) {
      # pp <- parse_path(path, chr = "")
      # r_state$radiant_rmd_name <<- path
      # r_state[[paste0("radiant_", input$rmd_type, "_name")]] <<- path 
      # r_state[[paste0("radiant_", input$rmd_generate, "_name")]] <<- path 
      # r_state[[paste0("radiant_", type, "_name")]] <<- path 
      r_state$radiant_rmd_name <<- path 
      report_save_content(path, type = "rmd")
    }
  })
}

observeEvent(input$rmd_load, {
  ## loading report from disk
  if (isTRUE(getOption("radiant.launch", "browser") == "viewer")) {
    path <- rstudioapi::selectFile(
      caption = "Select .Rmd, .md, or .html",
      filter = "Select .Rmd, .md, or .html (*)"
    )
    # } else {
      # path <- radiant.data::choose_files("Rmd", "rmd", "md", "html")
    # }
    pp <- parse_path(path, chr = "")
  } else {
    inFile <- input$rmd_load
    path <- inFile$datapath
    pp <- list(
      path = path,
      filename = inFile$name,
      fext = tools::file_ext(inFile$name)
    )
  }

  if (!is(path, "try-error") && !is_empty(path)) {
    if (pp$fext == "html") {
      ## based on http://rmarkdown.rstudio.com/r_notebook_format.html
      rmd <- try(rmarkdown::parse_html_notebook(pp$path), silent = TRUE)
      if (!is(rmd, "try-error")) {
        rmd <- paste0(rmd$rmd, collapse = "\n")
        r_state$radiant_rmd_name <<- sub("(\\.nb\\.html|\\.html)", ".Rmd", pp$path)
      } else {
        rmd <- "### The selected html file could not be parsed and does not contain rmarkdown content"
      }
    } else {
      # r_state$radiant_rmd_name <<- pp$path
      rmd <- paste0(readLines(pp$path), collapse = "\n")

      if (isTRUE(getOption("radiant.launch", "browser") == "viewer")) {
        r_state$radiant_rmd_name <<- pp$path
      } else {
        r_state$radiant_rmd_name <<- pp$filename
      }
    }

    ## update editor and remove yaml header if present
    shinyAce::updateAceEditor(session, "rmd_edit", 
      value = sub("^---\n(.*?)\n---\n*", "", rmd)
    )
  }
})

observeEvent(input$rmd_read_files, {
  cmd <- read_files(type = "rmd")
  if (!is_empty(cmd)) {
    update_report_fun(cmd, type = "rmd", read_files = TRUE)
  }
})

observeEvent(input$rmd_edit, {
  if (!identical(input$rmd_edit, rmd_example)) {
    r_state$rmd_edit <<- esc_slash(input$rmd_edit)
  }
})
